name: deploy_app

on:
  workflow_dispatch:
env:
  USERNAME: ubuntu 
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
  
      - name: Write secret to file
        run: |
          echo "${{ secrets.KEYPAIR }}" > cert.pem
          chmod 600 cert.pem

      - name: GET Public IP	
        run: |
          HOST=`aws ec2 describe-instances --filters 'Name=tag:Name,Values=test_exati'  --output text --query 'Reservations[*].Instances[*].PublicIpAddress'`
          echo "Host=$HOST" >> $GITHUB_ENV
          
      - name: deploy app
        run: |
           scp -i ./cert.pem -o StrictHostKeyChecking=no ./app/app.py $USERNAME@${{ env.Host }}:app/
           ssh -i ./cert.pem -o StrictHostKeyChecking=no $USERNAME@${{ env.Host }} "python app/app.py && sudo systemctl restart nginx"





